repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-added-large-files
  - repo: local
    hooks:
    - id: cargo-fmt
      name: cargo fmt
      entry: cargo fmt --all --check
      language: system
      types: [file]
      pass_filenames: false
      always_run: true
      verbose: true
    - id: cargo-clippy
      name: cargo clippy
      entry: cargo clippy --all -- -D warnings
      language: system
      types: [file]
      pass_filenames: false
      always_run: true
      verbose: true
